### PR TITLE
Address issue for avatar profile redirection

### PR DESCRIPTION
**Pull request by frenbu**
Hello Dave,
My edit should address issue "Avatar redirects to member-profile not member-acitvity #2"

Much appreciation for your work :)
Cheers,
Francesco

### CODE REVIEW

**Comment by davehakkens** [comment]
Hi Thanks for that Fenbu!  We added it, works! 
However we would like to have ANY use name/avatar over the entire website to link to their member-profile. Not member-activity 

Can you make that happen?

**Comment by frenbu** [comment]
ops thought it was solved globally :)
i'll look for it later!

F

2016-02-29 18:12 GMT+01:00 Dave Hakkens <notifications@github.com>:

**Comment by frenbu** [comment]
looks like it's now working only inside the member page if you click on the
avatar, right?

2016-02-29 19:09 GMT+01:00 Francesco Bussi <frenbu88@gmail.com>:

**Comment by davehakkens** [comment]
excact

**Pull request merged**
