### PR TITLE
Better image sizing for latestUploads widget

### PR DESCRIPTION
**Pull request by alromh87**

### CODE REVIEW

**Comment by alromh87** [comment]
You can now use "size"=>"medium" to select image size

**Comment by davehakkens** [comment]
can we also use small?

**Comment by davehakkens** [comment]
well just realised medium is actually already kinda small :D

**Comment by alromh87** [comment]
Anything that is configured at WP
Custom Image Sizes can be added using add_image_size
https://developer.wordpress.org/reference/functions/add_image_size/

This are default images sizes:
‘thumb’, ‘thumbnail’, ‘medium’, ‘large’, ‘post-thumbnail’

**Pull request merged**
